version: '2'
services:
  kafka:
    image: wurstmeister/kafka:latest
    ports: 
      - 9092:9092
    restart: always
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=34.204.88.242 
      - KAFKA_CREATE_TOPICS=test:1:1,det-twitter:1:1,det-paciente:1:1,det-hospital:1:1,det-medico:1:1,det-fornecedor:1:1,tri-twitter:1:1,tri-paciente:1:1,tri-hospital:1:1,tri-medico:1:1,tri-fornecedor:1:1,msg-paciente:1:1,msg-hospital:1:1,msg-medico:1:1,msg-fornecedor:1:1,msg-autoridade:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_RETENTION_MINUTES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports: 
      - 2181:2181
    restart: always

